export default {
    UPDATE_FECHA: "UPDATE_FECHA",
    GET_ESTRENOS: "GET_ESTRENOS",
    GET_ESTRENOS_PENDING: "GET_ESTRENOS_PENDING",
    GET_ESTRENOS_FULFILLED: "GET_ESTRENOS_FULFILLED",
    GET_ESTRENOS_REJECTED: "GET_ESTRENOS_REJECTED",

    //acciones para proximos estrenos:
    GET_PROXIMOS_ESTRENOS: "GET_PROXIMOS_ESTRENOS",
    GET_PROXIMOS_ESTRENOS_FULFILLED: "GET_PROXIMOS_ESTRENOS_FULFILLED",
    GET_PROXIMOS_ESTRENOS_PENDING: "GET_PROXIMOS_ESTRENOS_PENDING",
    GET_PROXIMOS_ESTRENOS_REJECTED: "GET_PROXIMOS_ESTRENOS_REJECTED",


    //acciones para creditos:
    GET_CREDITOS: "GET_CREDITOS",
    GET_CREDITOS_FULFILLED: "GET_CREDITOS_FULFILLED",
    GET_CREDITOS_PENDING: "GET_CREDITOS_PENDING",
    GET_CREDITOS_REJECTED: "GET_CREDITOS_REJECTED",


    //detalles de las peliculas
    GET_PELICULA_DETALLE: "GET_PELICULA_DETALLE",
    GET_PELICULA_DETALLE_FULFILLED: "GET_PELICULA_DETALLE_FULFILLED",
    GET_PELICULA_DETALLE_PENDING: "GET_PELICULA_DETALLE_PENDING",
    GET_PELICULA_DETALLE_REJECTED: "GET_PELICULA_REJECTED",


    //busqueda:

    GET_BUSQUEDA: "GET_BUSQUEDA",
    GET_BUSQUEDA_FULFILLED: "GET_BUSQUEDA_FULFILLED",
    GET_BUSQUEDA_PENDING: "GET_BUSQUEDA_PENDING",
    GET_BUSQUEDA_REJECTED: "GET_BUSQUEDA_REJECTED",
    CLEAR_SEARCH: "CLEAR_SEARCH",

    // Trailers

    GET_TRAILER: 'GET_TRAILER',
    GET_TRAILER_FULFILLED: 'GET_TRAILER_FULFILLED',
    GET_TRAILER_PENDING: 'GET_TRAILER_PENDING',
    GET_TRAILER_REJECTED: 'GET_TRAILER_REJECTED',

}


///// POR FAVOR NO OLVIDAR REVISAR QUE EL CODIGO NO CONTENGA ALGUN ESPACIO DE TEXTO ENTRE COMILLAS